### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by riadd** [chitsaou/vscode-coffeescript-support#1]
Hello, thanks for the work on the extension!

I'm having issues getting it to run on my system. Opening symbols for my file, I'm getting the following error message:

`[Error - 11:42:45] Request textDocument/documentSymbol failed.
  Message: Request textDocument/documentSymbol failed with message: ENOENT: no such file or directory, open 'd:\d%3A\projects\curiousexped\curiousexpedition\prototype-html\coffeescript\party.coffee'
  Code: -32603 `

I'm not sure how the "d%3A" part gets injected into the path name. It should be "d:\projects\curiousexped\curiousexpedition\prototype-html\coffeescript\party.coffee" instead.

I'm on Windows 10. VS Code 1.18.1.

**Comment by yorkxin** [comment]
`d%3A` is `d:` so I believe there is something wrong when getting the full path. 

I found a similar issue here: https://github.com/Microsoft/vscode/issues/2990

But I believe the issue is that I removed `file://` improperly: https://github.com/chitsaou/vscode-coffeescript-support/blob/master/server/src/utils/fileReader.ts#L5

**Comment by riadd** [comment]
Maybe it should use [URL.file](https://github.com/Microsoft/vscode-uri/blob/2255aa25f205d1364666a6b6f9dcc51e46d403bf/lib/index.ts#L212) instead of URL.parse?

Any chance you could try that out?

**Comment by zdenko** [comment]
I have a similar problem (macOS) with character `@` in the path, which is encoded to `%40`.
I've solved it by changing https://github.com/chitsaou/vscode-coffeescript-support/blob/master/server/src/utils/fileReader.ts#L5 to
```javascript
  return URL.parse(decodeURIComponent(uri)).path
```

**Comment by yorkxin** [comment]
@zdenko Glad to hear that. If you don't mind could you send a pull request containing this patch? I'll find a way to test it on Windows.

**Comment by yorkxin** [comment]
@riadd I am on macOS so testing it on Windows was something I didn't do (sorry). But since you reported the issue, I will test it on a Windows virtual machine.

**Comment by yorkxin** [comment]
@riadd @zdenko 

I think I found a way to fix it, and checked on both macOS and Windows.

Here is the pre-release: https://github.com/chitsaou/vscode-coffeescript-support/releases/tag/v0.1.3beta1

Could you check it and let me know if it works as expected?

Thanks!

**Comment by zdenko** [comment]
It works 👍

**Comment by riadd** [comment]
Works for me as well (windows 10). Thank you!

**Comment by yorkxin** [comment]
Thanks for your help!

Just released a new version. Please check it :)
