### ISSUE TITLE
Feature request: Go to definition in workspace

### ISSUE THREAD

**Issue by ilteris** [chitsaou/vscode-coffeescript-support#7]
Thanks so much for this extension. I know it's planned
>Show all All Symbol Definitions in Workspace ("Go to symbol in workspace" command)

Can't wait to have it! I see a feature branch on it:) Is there any timeline for release? :) 

Thank you so much.

**Comment by yorkxin** [comment]
Thanks for interesting to it! 

The pull request #6 is not ready to merge yet before I resolve some blockers. Particularly for performance issue.

If you want to try it, you can find a beta version at https://github.com/chitsaou/vscode-coffeescript-support/releases

Cheers!
