### ISSUE TITLE
Symbols no longer found

### ISSUE THREAD

**Issue by brucedjones** [chitsaou/vscode-coffeescript-support#9]
Since updating VSCode to 1.28.2 I get "No symbols found" for coffeescript files.

**Comment by yorkxin** [comment]
Hi, what command did you perform? (Search for symbol across files? Or within a file?)

**Comment by brucedjones** [comment]
Nothing shows in the outline ("No symbols found in document") or breadcrumbs, and cmd + shift + o shows "No symbols found".

I tried disabling and reenabling the extension, also tried reloading vscode. Neither helped.

**Comment by yorkxin** [comment]
Hi, I just tried locally, and it works for me. I have a brand-new installed macOS and VSCode.

- Visual Studio Code 1.28.2
- coffeescript-support 0.1.4

<img width="750" alt="screen shot 2018-11-08 at 23 30 22" src="https://user-images.githubusercontent.com/10737/48204920-6a2dc800-e3ae-11e8-864b-d21707b71c13.png">

---

Would you also try a beta version of 0.2.0? (In fact I haven't touch the beta for long time. I'll probably just ship it recently)

https://github.com/chitsaou/vscode-coffeescript-support/releases

**Comment by brucedjones** [comment]
Ok strange, it is now working for me (after giving it time and nothing else..) Thanks for the prompt response. Closing this.
